"""update models

Revision ID: 25e863bd89f4
Revises: b496913f0e30
Create Date: 2024-01-20 12:17:47.576283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e863bd89f4'
down_revision: Union[str, None] = 'b496913f0e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('_hashed_password', sa.LargeBinary(), nullable=False))
    op.drop_column('usermodel', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usermodel', sa.Column('hashed_password', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('usermodel', '_hashed_password')
    # ### end Alembic commands ###
